const products = [
  {
    name: 'Pizza Margherita',
    category: 'pizzas',
    price: 5.5,
    image: '/images/1.png',
  },
  {
    name: 'Pizza Prosciutto',
    category: 'pizzas',
    price: 9.8,
    image: '/images/2.png',
  },
  {
    name: 'Pizza Pepperoni',
    category: 'pizzas',
    price: 12.95,
    image: '/images/3.png',
  },
  {
    name: 'Pizza BBQ Bacon',
    category: 'pizzas',
    price: 20,
    image: '/images/4.png',
  },
  {
    name: 'Pizza Quattro Formaggio',
    category: 'pizzas',
    price: 11.8,
    image: '/images/5.png',
  },
  {
    name: 'Pizza Napoletana',
    category: 'pizzas',
    price: 10,
    image: '/images/6.png',
  },
  {
    name: 'Chicken Burger',
    category: 'burgers',
    price: 4,
    image: '/images/7.png',
  },
  {
    name: 'GenerousJack Burger',
    category: 'burgers',
    price: 7.95,
    image: '/images/8.png',
  },
  {
    name: 'BigMac Burger',
    category: 'burgers',
    price: 4.5,
    image: '/images/9.png',
  },
  {
    name: 'Bacon Burger',
    category: 'burgers',
    price: 6,
    image: '/images/10.png',
  },
  {
    name: 'Classic Burger',
    category: 'burgers',
    price: 3.25,
    image: '/images/11.png',
  },
  {
    name: 'Fanta Orange',
    category: 'soft drinks',
    price: 2.5,
    image: '/images/12.png',
  },
  {
    name: 'Coca-Cola',
    category: 'soft drinks',
    price: 2.5,
    image: '/images/13.png',
  },

  {
    name: 'Sprite',
    category: 'soft drinks',
    price: 2.5,
    image: '/images/14.png',
  },
  {
    name: 'Coca-Cola Zero',
    category: 'soft drinks',
    price: 2.5,
    image: '/images/15.png',
  },
  {
    name: 'Spa Reine',
    category: 'soft drinks',
    price: 2,
    image: '/images/16.png',
  },
  {
    name: 'Spa Intense',
    category: 'soft drinks',
    price: 2,
    image: '/images/17.png',
  },
  {
    name: 'White Vodka Redbull',
    category: 'cocktails',
    price: 11.5,
    image: '/images/18.png',
  },
  {
    name: 'Red Vodka Redbull',
    category: 'cocktails',
    price: 11.5,
    image: '/images/19.png',
  },
  {
    name: 'Havana Mojito',
    category: 'cocktails',
    price: 12.5,
    image: '/images/20.png',
  },
  {
    name: 'Bombay Gin Tonic',
    category: 'cocktails',
    price: 14,
    image: '/images/21.png',
  },
  {
    name: 'Rosé Wine',
    category: 'wine',
    price: 4.5,
    image: '/images/22.png',
  },
  {
    name: 'White Wine',
    category: 'wine',
    price: 4.5,
    image: '/images/23.png',
  },
  {
    name: 'Tequila Sunrise',
    category: 'cocktails',
    price: 8.5,
    image: '/images/24.png',
  },
  {
    name: 'Sex On The Beach',
    category: 'cocktails',
    price: 15,
    image: '/images/25.png',
  },
  {
    name: 'Jupiler',
    category: 'beers',
    price: 2.5,
    image: '/images/26.png',
  },
  {
    name: 'Duvel',
    category: 'beers',
    price: 3.5,
    image: '/images/27.png',
  },
  {
    name: 'Carlsberg',
    category: 'beers',
    price: 2.7,
    image: '/images/28.png',
  },
  {
    name: 'Stella Artois',
    category: 'beers',
    price: 2.5,
    image: '/images/29.png',
  },
  {
    name: 'La Chouffe',
    category: 'beers',
    price: 3.2,
    image: '/images/30.png',
  },
  {
    name: 'Red Wine',
    category: 'wine',
    price: 4.5,
    image: '/images/31.png',
  },
];
module.exports = products;
